/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SyllabusRouteImport } from './routes/syllabus'
import { Route as SyllabusRouteImport } from './routes/syllabus'
import { Route as RevisionRouteImport } from './routes/revision'
import { Route as PyqRouteImport } from './routes/pyq'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as MentorRouteImport } from './routes/mentor'
import { Route as InstitutionsRouteImport } from './routes/institutions'
import { Route as CurrentAffairsRouteImport } from './routes/current-affairs'
import { Route as AnswersRouteImport } from './routes/answers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SyllabusRoute = SyllabusRouteImport.update({
  id: '/syllabus',
  path: '/syllabus',
  getParentRoute: () => rootRouteImport,
} as any)
const SyllabusRoute = SyllabusRouteImport.update({
  id: '/syllabus',
  path: '/syllabus',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisionRoute = RevisionRouteImport.update({
  id: '/revision',
  path: '/revision',
  getParentRoute: () => rootRouteImport,
} as any)
const PyqRoute = PyqRouteImport.update({
  id: '/pyq',
  path: '/pyq',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorRoute = MentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionsRoute = InstitutionsRouteImport.update({
  id: '/institutions',
  path: '/institutions',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrentAffairsRoute = CurrentAffairsRouteImport.update({
  id: '/current-affairs',
  path: '/current-affairs',
  getParentRoute: () => rootRouteImport,
} as any)
const AnswersRoute = AnswersRouteImport.update({
  id: '/answers',
  path: '/answers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/answers': typeof AnswersRoute
  '/current-affairs': typeof CurrentAffairsRoute
  '/institutions': typeof InstitutionsRoute
  '/mentor': typeof MentorRoute
  '/planner': typeof PlannerRoute
  '/pyq': typeof PyqRoute
  '/revision': typeof RevisionRoute
  '/syllabus': typeof SyllabusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/answers': typeof AnswersRoute
  '/current-affairs': typeof CurrentAffairsRoute
  '/institutions': typeof InstitutionsRoute
  '/mentor': typeof MentorRoute
  '/planner': typeof PlannerRoute
  '/pyq': typeof PyqRoute
  '/revision': typeof RevisionRoute
  '/syllabus': typeof SyllabusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/answers': typeof AnswersRoute
  '/current-affairs': typeof CurrentAffairsRoute
  '/institutions': typeof InstitutionsRoute
  '/mentor': typeof MentorRoute
  '/planner': typeof PlannerRoute
  '/pyq': typeof PyqRoute
  '/revision': typeof RevisionRoute
  '/syllabus': typeof SyllabusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/answers'
    | '/current-affairs'
    | '/institutions'
    | '/mentor'
    | '/planner'
    | '/pyq'
    | '/revision'
    | '/syllabus'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/answers'
    | '/current-affairs'
    | '/institutions'
    | '/mentor'
    | '/planner'
    | '/pyq'
    | '/revision'
    | '/syllabus'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/answers'
    | '/current-affairs'
    | '/institutions'
    | '/mentor'
    | '/planner'
    | '/pyq'
    | '/revision'
    | '/syllabus'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnswersRoute: typeof AnswersRoute
  CurrentAffairsRoute: typeof CurrentAffairsRoute
  InstitutionsRoute: typeof InstitutionsRoute
  MentorRoute: typeof MentorRoute
  PlannerRoute: typeof PlannerRoute
  PyqRoute: typeof PyqRoute
  RevisionRoute: typeof RevisionRoute
  SyllabusRoute: typeof SyllabusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/syllabus': {
      id: '/syllabus'
      path: '/syllabus'
      fullPath: '/syllabus'
      preLoaderRoute: typeof SyllabusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revision': {
      id: '/revision'
      path: '/revision'
      fullPath: '/revision'
      preLoaderRoute: typeof RevisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pyq': {
      id: '/pyq'
      path: '/pyq'
      fullPath: '/pyq'
      preLoaderRoute: typeof PyqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor': {
      id: '/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof MentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutions': {
      id: '/institutions'
      path: '/institutions'
      fullPath: '/institutions'
      preLoaderRoute: typeof InstitutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/current-affairs': {
      id: '/current-affairs'
      path: '/current-affairs'
      fullPath: '/current-affairs'
      preLoaderRoute: typeof CurrentAffairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/answers': {
      id: '/answers'
      path: '/answers'
      fullPath: '/answers'
      preLoaderRoute: typeof AnswersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnswersRoute: AnswersRoute,
  CurrentAffairsRoute: CurrentAffairsRoute,
  InstitutionsRoute: InstitutionsRoute,
  MentorRoute: MentorRoute,
  PlannerRoute: PlannerRoute,
  PyqRoute: PyqRoute,
  RevisionRoute: RevisionRoute,
  SyllabusRoute: SyllabusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
